plugins {
    id 'com.android.application'
}

android {
    namespace 'prts.user.authorization0'
    compileSdk 34

    defaultConfig {
        applicationId "prts.user.authorization0"
        minSdk 19
        //noinspection ExpiredTargetSdkVersion
        targetSdk 28
        versionCode 20
        versionName "2.0"
    }

    signingConfigs {
        release {
            storeFile file("D:\\debug.keystore")
            storePassword "android"
            keyAlias "minesms"
            keyPassword "android"
        }
        debug {
            storeFile file("../platform.keystore")
            storePassword "android"
            keyAlias "platform"
            keyPassword "android"
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.release
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            zipAlignEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    implementation fileTree(dir: "libs", include: ["*.jar"])
}
